In [5]:
pip install pandas

Collecting pandas
  Using cached pandas-3.0.1-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\dell\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.1-cp313-cp313-win_amd64.whl (9.7 MB)
Installing collected packages: pandas
Successfully installed pandas-3.0.1
Note: you may need to restart the kernel to use updated packages.

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/pandas/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/pandas/

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: c:\Users\Dell\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r'C:\Users\Dell\Downloads\customers_data.csv') #read csv

In [13]:
# Inspecting the DataFrame

df.shape          # (rows, columns)

(100, 12)

In [14]:
df.head()         # First 5 rows

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

In [15]:
df.tail()         # Last 5 rows

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [16]:
df.columns        # List of column names

Index(['Index', 'Customer Id', 'First Name', 'Last Name', 'Company', 'City',
       'Country', 'Phone 1', 'Phone 2', 'Email', 'Subscription Date',
       'Website'],
      dtype='str')

In [17]:
df.info()         # Summary (dtypes, nulls)

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              100 non-null    int64
 1   Customer Id        100 non-null    str
 2   First Name         100 non-null    str
 3   Last Name          100 non-null    str
 4   Company            100 non-null    str
 5   City               100 non-null    str
 6   Country            100 non-null    str
 7   Phone 1            100 non-null    str
 8   Phone 2            100 non-null    str
 9   Email              100 non-null    str
 10  Subscription Date  100 non-null    str
 11  Website            100 non-null    str
dtypes: int64(1), str(11)
memory usage: 9.5 KB

In [4]:

  # Filter: Selects rows where 'City' is one of the listed values ('Delhi' OR 'Pune').

df[df['City'].isin(['Delhi', 'Pune'])]

Empty DataFrame
Columns: [Index, Customer Id, First Name, Last Name, Company, City, Country, Phone 1, Phone 2, Email, Subscription Date, Website]
Index: []

In [18]:
# --- Basic Selection ---

df['Email']                     # Selects one column by name (returns a Series).

0           zunigavanessa@smith.info
1                    vmata@colon.com
2                beckycarr@hogan.com
3        stanleyblackwell@benson.org
4            colinalvarado@miles.net
                   ...
95                  hhart@jensen.com
96                 vkemp@ferrell.com
97                  swagner@kane.org
98    mccarthystephen@horn-green.biz
99            colleen91@faulkner.biz
Name: Email, Length: 100, dtype: str

In [ ]:
df[['Company','City','Country']] # Selects multiple columns by name (returns a DataFrame).

,Company,City,Country
0,Rasmussen Group,East Leonard,Chile
1,Vega-Gentry,East Jimmychester,Djibouti
2,Murillo-Perry,Isabelborough,Antigua and Barbuda
3,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic
4,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic)
...,...,...,...
95,Carey LLC,East Richard,Guyana
96,"Ware, Burns and Oneal",New Bradview,Sri Lanka
97,Schmitt-Jones,Ortegaland,Solomon Islands
98,Fitzgerald-Harrell,Lake Elijahview,Aruba
99,"Le, Nash and Cross",Judymouth,Honduras

In [21]:
# --- Label-Based Indexing (.loc) ---

df.loc[8]                           # Selects the row with the label '0'.

Index                                       9
Customer Id                   C2dE4dEEc489ae0
First Name                             Sheryl
Last Name                              Meyers
Company                        Browning-Simon
City                             Robersonstad
Country                                Cyprus
Phone 1                     854-138-4911x5772
Phone 2                   +1-448-910-2276x729
Email                 mariokhan@ryan-pope.org
Subscription Date                  2020-01-13
Website              https://www.bullock.net/
Name: 8, dtype: object

In [ ]:
df.loc[0:2, ['Company', 'City']]        # Label-based slice: Rows 0 through 2, and columns

           Company               City
0  Rasmussen Group       East Leonard
1      Vega-Gentry  East Jimmychester
2    Murillo-Perry      Isabelborough

In [ ]:
# --- Data Filtering (Conditional Selection) ---need to check with anwar bro 

df['date'] = pd.to_datetime(df['Subscription Date'])                        # Filter: Selects rows where 'Age' is greater than 25 (uses a boolean mask).
filtered_df = df[df['Subscription Date'] > '2010-10-03']

In [ ]:
df[
    (df['Country'] == 'Sri lanka') &
    (df['City'] == 'East Leonard')
]                                               # Filter:  (multiple conditions require parentheses and '&').

Empty DataFrame
Columns: [Index, Customer Id, First Name, Last Name, Company, City, Country, Phone 1, Phone 2, Email, Subscription Date, Website, date]
Index: []

In [5]:
df[df['Country'].isin(['Chile', 'Oman'])]

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
15,16,8cad0b4CBceaeec,Miranda,Beasley,Singleton and Sons,Desireeshire,Oman,540.085.3135x185,+1-600-462-6432x21881,vduncan@parks-hardy.com,2022-04-12,http://acosta.org/
83,84,78C06E9b6B3DF20,Chad,Davidson,Garcia-Jimenez,South Joshuashire,Oman,8275702958,(804)842-4715,justinwalters@jimenez.com,2021-11-15,http://www.garner-oliver.com/

In [ ]:

df['Age'] = df['Age'] + 1                                       # Updates existing 'Age' column by adding 1 to every value.
df['Gender'].replace({'M':'Male', 'F': 'Female'}, inplace=True) # Replaces 'M' and 'F' values with full names in the 'Gender' column.

In [9]:
#Adding / Modifying Columns

df['Salary'] = pd.Series([50000, 60000, 55000, 70000])               # Adds new 'Salary' column from a list.
                              # Adds calculated 'Bonus' column (vectorized operation).

In [11]:
df.columns

Index(['Index', 'Customer Id', 'First Name', 'Last Name', 'Company', 'City',
       'Country', 'Phone 1', 'Phone 2', 'Email', 'Subscription Date',
       'Website', 'Salary'],
      dtype='str')

In [12]:
df.shape

(100, 13)

In [13]:
df.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website,Salary
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/,50000.0
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/,60000.0
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/,55000.0
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/,70000.0
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/,NaN

In [14]:
# Adds a Bonus column that is 10% of each person's Salary
df['Bonus'] = df['Salary'] * 0.10

# You can also add them together for a Total Pay column
df['Total_Pay'] = df['Salary'] + df['Bonus']

In [15]:
df.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website,Salary,Bonus,Total_Pay
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/,50000.0,5000.0,55000.0
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/,60000.0,6000.0,66000.0
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/,55000.0,5500.0,60500.0
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/,70000.0,7000.0,77000.0
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/,NaN,NaN,NaN

In [ ]:
df['Salary'] = df['Salary'] + 7       

df.head()                                # Updates existing 'salary' column by adding 7 to every value.

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website,Salary,Bonus,Total_Pay
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/,50014.0,5000.0,55000.0
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/,60014.0,6000.0,66000.0
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/,55014.0,5500.0,60500.0
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/,70014.0,7000.0,77000.0
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/,NaN,NaN,NaN

In [18]:
# Replaces 'Srilanka' 
df['Country'].replace({'Srilanka':'Lankan'}, inplace=True)

C:\Users\Dell\AppData\Local\Temp\ipykernel_19468\4057549128.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Country'].replace({'Srilanka':'Lankan'}, inplace=True)

0                          Chile
1                       Djibouti
2            Antigua and Barbuda
3             Dominican Republic
4     Slovakia (Slovak Republic)
                 ...
95                        Guyana
96                     Sri Lanka
97               Solomon Islands
98                         Aruba
99                      Honduras
Name: Country, Length: 100, dtype: str

In [19]:
# Renames columns (modifies the DataFrame directly).
df.rename(columns={'Company':'Industry', 'City':'Location'}, inplace=True)

In [20]:
df.head()

,Index,Customer Id,First Name,Last Name,Industry,Location,Country,Phone 1,Phone 2,Email,Subscription Date,Website,Salary,Bonus,Total_Pay
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/,50014.0,5000.0,55000.0
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/,60014.0,6000.0,66000.0
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/,55014.0,5500.0,60500.0
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/,70014.0,7000.0,77000.0
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/,NaN,NaN,NaN

In [21]:
#deleting rows and columns:

df.drop('Bonus', axis=1, inplace=True)      # Drops the 'Bonus' column (axis=1) permanently (inplace=True).
df.drop(2, axis=0, inplace=True)            # Drops the row with index label '2' (axis=0) permanently.
# Reminder: axis=0 refers to rows, axis=1 refers to columns.

In [22]:
df.head()

,Index,Customer Id,First Name,Last Name,Industry,Location,Country,Phone 1,Phone 2,Email,Subscription Date,Website,Salary,Total_Pay
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/,50014.0,55000.0
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/,60014.0,66000.0
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/,70014.0,77000.0
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/,NaN,NaN
5,6,2d08FB17EE273F4,Aimee,Downs,Steele Group,Chavezborough,Bosnia and Herzegovina,(283)437-3886x88321,999-728-1637,louis27@gilbert.com,2020-02-25,http://www.berger.net/,NaN,NaN

In [24]:
#sorting data:
df.sort_values(by='Salary')                     # Sorts the DataFrame by the values in the 'Age' column (ascending is the default).

,Index,Customer Id,First Name,Last Name,Industry,Location,Country,Phone 1,Phone 2,Email,Subscription Date,Website,Salary,Total_Pay
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/,50014.0,55000.0
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/,60014.0,66000.0
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/,70014.0,77000.0
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/,NaN,NaN
5,6,2d08FB17EE273F4,Aimee,Downs,Steele Group,Chavezborough,Bosnia and Herzegovina,(283)437-3886x88321,999-728-1637,louis27@gilbert.com,2020-02-25,http://www.berger.net/,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/,NaN,NaN
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/,NaN,NaN
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/,NaN,NaN
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/,NaN,NaN
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/,NaN,NaN

In [25]:
df.sort_values(by='Salary', ascending=False) # Sorts the DataFrame by 'Salary' in descending order.

,Index,Customer Id,First Name,Last Name,Industry,Location,Country,Phone 1,Phone 2,Email,Subscription Date,Website,Salary,Total_Pay
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/,70014.0,77000.0
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/,60014.0,66000.0
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/,50014.0,55000.0
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/,NaN,NaN
5,6,2d08FB17EE273F4,Aimee,Downs,Steele Group,Chavezborough,Bosnia and Herzegovina,(283)437-3886x88321,999-728-1637,louis27@gilbert.com,2020-02-25,http://www.berger.net/,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/,NaN,NaN
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/,NaN,NaN
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/,NaN,NaN
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/,NaN,NaN
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/,NaN,NaN